# Generated by Django 4.0.3 on 2022-03-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='api_key',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AuthenticationToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pay.apikey')),
            ],
        ),
    ]
