# Generated by Django 4.0.3 on 2022-03-15 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0002_alter_apikey_api_key_authenticationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationtoken',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 15, 21, 11, 3, 203791, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
