# Generated by Django 4.0.3 on 2022-03-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0004_order_alter_simpleuser_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authenticationtoken',
            old_name='token',
            new_name='auth_token',
        ),
    ]
